# Generated by Django 4.1.7 on 2023-03-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("0-2", "0-2 years"),
                            ("3-5", "3-5 years"),
                            ("6-8", "6-8 years"),
                            ("9-12", "9-12 years"),
                            ("12+", "12+ years"),
                        ],
                        max_length=50,
                    ),
                ),
                ("job_location", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100)),
                ("company_website", models.URLField()),
                ("apply_link", models.URLField()),
            ],
        ),
    ]
